from typing import Any, Callable

class Stream: ...

class Watch:
    def __init__(self, return_type: Any = None): ...
    def stop(self) -> None: ...
    def stream(self, func: Callable[...], *args: Any, **kwargs: Any) -> Any: ...
    def unmarshal_event(self, data: str, response_type: Any) -> dict[str, Any]: ...
