from typing import Any, Callable

from .client import ApiClient

class Stream: ...

class Watch:
    _raw_return_type: Any
    _stop: bool
    _api_client: ApiClient
    resource_version: str | None

    def __init__(self, return_type: Any = None): ...
    def stop(self) -> None: ...
    def stream(self, func: Callable[...], *args: Any, **kwargs: Any) -> Any: ...
    def unmarshal_event(self, data: str, response_type: Any) -> dict[str, Any]: ...
